# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'demo' do

pod 'AFNetworking','~>2.2.1'
pod 'Reachability', '~> 3.2'
end

target 'demoTests' do

end

